# Project
app_expertise_project_list:
    path:     /list
    defaults: { _controller: 'PuzzleAppExpertiseBundle:Project:list' }
    
app_expertise_project_show:
    path:     /{id}
    defaults: { _controller: 'PuzzleAppExpertiseBundle:Project:show' }